### ISSUE TITLE
Throw error when item not stored (Suggestion).

### ISSUE THREAD

**Issue by aurbina83** [driftyco/ionic-storage#25]
Instead of returning null for an item that doesn't exist, wouldn't it be better to return an error?

```
this.storage.get('item').then(data => {
    this.something = data;
}, err => {
    alert('Nothing here');
});
```

NativeStorage does this which makes writing out code easier instead of having if(!data) in all of my storage calls.

**Comment by NoNameProvided** [comment]
I support this idea as well. I guess the current scenario was selected because this way a rejection means operational error (localstorage error, indexdb error) happened, while a `null`  return value means programmer error.

Still I support the idea of rejecting the promise when no data is found. To distinguish between missing value and operational errors we can use a special `NotFoundError` type. 

A minimal implementation: 

```typescript
// not-found.error.ts
export class NotFoundError {
    public stack: string;
    public name: string = 'NotFoundError';

    constructor(public message: string) {
        super();
        if ((Error as ExtendedErrorConstructor).captureStackTrace) {
            (Error as ExtendedErrorConstructor).captureStackTrace(this, this.constructor);
        } else {
            this.stack = (new Error()).stack;
        }
    }

    toString() {
      return `[${this.name}] ${this.message}`;
    }
}

// in storage.ts
import { NotFoundError } from './not-found.error.ts'

/**
   * Get the value associated with the given key.
   * @param key the key to identify this value
   * @return Promise that resolves with the value
   */
  get(key: string): Promise<any> {
    return new Promise( (resolve, reject) => {
      this._dbPromise.then(db => {
        const value = db.getItem(key);

        value ? resolve(value) : reject(new NotFoundError())
      });
    });
  }
```

**Comment by mlynch** [comment]
Thanks for the comments. I don't know if I'm 100% supportive of this because it's not an error, the item just doesn't exist. Given that I don't think it's a big enough improvement to warrant breaking the API, I think I'm going to close for now and if other people have thoughts we can keep the conversation going.
