### ISSUE TITLE
Dealing with functions for storage.get

### ISSUE THREAD

**Issue by dericeira** [driftyco/ionic-storage#32]
I have a function verify if a user exists:

```
userIsLogged() {
    this.storage.get('token').then((token) => {
      if (token) {
        return true;
      }
      else {
        return false;
      }
    }); 
  }
```

But, when I call this function, it should return a boolean, but It's returning a void. Because storage.get has a promise. How can I deal with this. I'm using this function userIsLogged() to show or hide an element in the view.

**Comment by tcrespog** [comment]
You'll need to understand how asynchronous code and JavaScript promises work in order to achieve what you're trying.
The code you have posted returns another Promise containing true or false as the fulfillment value, you could manage that Promise in turn in order to store the value in a variable at the target place:
`userIsLogged().then( (isLogged) => this.isLogged = isLogged)`

To understand JavaScript Promises better a good resource is https://developer.mozilla.org/en-US/docs/Mozilla/JavaScript_code_modules/Promise.jsm/Promise.

**Comment by mlynch** [comment]
Thanks, you'll want to use promises as @tcrespog mentioned. This is just one of those things.
