### ISSUE TITLE
useFactory does not exist in type StorageConfig

### ISSUE THREAD

**Issue by gnujeremie** [driftyco/ionic-storage#84]
Just updated to 2.0.0, and when I try to use 
```IonicStorageModule.forRoot({ useFactory: provideStorage })```

I get a compilation error saying

```Argument of type '{ useFactory: () => Storage; }' is not assignable to parameter of type 'StorageConfig'. Object literal may only specify known properties, and 'useFactory' does not exist in type 'StorageConfig'.```

**Comment by ghenry22** [comment]
yeh I get this as well following the comments in the ts file for adding configuration to storage 2.0

This is currently blocking me from updating to latest ionic as storage 2.0.0 is a requirement.

**Comment by ghenry22** [comment]
@gnujeremie 

comment out that whole export function provideStorage section

Make your imports look like this instead:

```
  imports: [
    IonicModule.forRoot(MyApp, config),
    IonicStorageModule.forRoot({
      name: '__substreamer3',
     // storeName: '__substreamer3kv',
      driverOrder: ['sqlite', 'websql', 'indexeddb', 'localstorage']
    })
  ],
```
otherwise follow the 2.0.0 instructions and you're good to go.  Had to dig through the storage.ts file for a bit to find what it was actually expecting to be passed in for config.

**Comment by gnujeremie** [comment]
@ghenry22  Yes that's what I found out too in the source code too afterwards :)
