### ISSUE TITLE
.get() Does not assign value to a variable

### ISSUE THREAD

**Issue by LuisHCK** [driftyco/ionic-storage#97]
I want to save the returned value to a variable, but it returns undefined,
```
var mytoken
      this.storage.get('token').then((token)=>{
        mytoken = String(token)
     });

     console.log("mytoken: "+ mytoken)
```

in console i have `mytoken: undefined`
what am I doing wrong?
pd: i am noob :(

```
Your system information:

Cordova CLI: 6.5.0 
Ionic Framework Version: 3.0.1
Ionic CLI Version: 2.2.2
Ionic App Lib Version: 2.2.1
Ionic App Scripts Version: 1.3.0
ios-deploy version: Not installed
ios-sim version: Not installed
OS: Linux 4.10
Node Version: v7.7.3
Xcode version: Not installed
```

**Comment by LuisHCK** [comment]
I managed to make it work!
Instead of assigning the data to a variable, I call a function
```
this.storage.get('token').then((token)=>{
        this.getData(token);
     });
```

**Comment by jose1914luis** [comment]
Overload the value and take the data:
this.storage.get('txt_key').then((val) => {
      this.apikey = ('&' + val).substring(1, val.length+1);
});

**Comment by harshm90** [comment]
> I managed to make it work!
> Instead of assigning the data to a variable, I call a function
> 
> ```
> this.storage.get('token').then((token)=>{
>         this.getData(token);
>      });
> ```

can u please elaborate :( 
I am facing same issue but unable to figure it out

**Comment by kensodemann** [comment]
@harshm90 - what does your code look like?

The OPs code was this:

```
var mytoken;
this.storage.get('token').then((token)=>{
  mytoken = String(token)
});

console.log("mytoken: "+ mytoken)
```

But the problem there is simply a poor understanding of how promises work.

Obviously `mytoken` will be undefined where it is used in the console.log() since the callback given to the `.then()` will not execute until at least the next loop through the task queue, perhaps even later.

**Comment by harshm90** [comment]
> @harshm90 - what does your code look like?
> 
> The OPs code was this:
> 
> ```
> var mytoken
> this.storage.get('token').then((token)=>{
>   mytoken = String(token)
> });
> 
> console.log("mytoken: "+ mytoken)
> ```
> But the problem there is simply a poor understanding of how promises work.
> 
> Obviously `mytoken` will be undefined where it is used in the console.log() since the callback given to the `.then()` will not execute until at least the next loop through the task queue, perhaps even later.
> 
> This would make much more sense:
> 
> ```
> let mytoken;
> this.storage.get('token').then((token)=>{
>   mytoken = String(token);
>   console.log("mytoken: "+ mytoken);
> });
> ```
> Or using `async/await`...

**Method :- 1**

```
getData() {
        return this.storage.get('products')
          .then(res => {
            return this.cart = res;
          });;
      }

```
This gives me output as Undefined

**Comment by kensodemann** [comment]
Out of context, it is hard to determine what is going on, but a few things you can try:

First, make sure storage is ready... This is rarely an issue, but it could be:

```
getData() {
  return this.storage.ready()
    .then(() =>
      this.storage.get('products')
      .then(res => {
        console.log('res:', res);
        return this.cart = res;
      })
    );
}
```

I also added a `console.log()` to examine the actual return just to see that the problem is actually there and not elsewhere.

Double check the `set()` call to make sure you are using exactly the same key. Better yet, create an enum of all of your keys and use that when calling these functions.

Make sure you have actually set something... If you are running this in a browser, open your dev tools and check whichever storage mechanism you happen to be using and see that the value you expect is actually set properly.

If all else fails, post a sample app that has the same issue and I will have a quick look. I use the storage module in a few apps and have never had an issue, so you likely just missed something. I would be happy to have a look at it to help.
